// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-spaces.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient } from "npm:@supabase/supabase-js@^2.52.1";
import { z } from "npm:zod@^3.23.8";
function createPublicSupabase() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_spaces_default = defineTool({
  name: "search_spaces",
  title: "Search neuro-friendly workspaces",
  description: "Search the NeuroIndex directory of neuro-friendly workspaces, coworking spaces, and meeting rooms. Supports filtering by location, certification, minimum neuro score, and free-text search over titles, descriptions, locations, and amenities.",
  inputSchema: {
    query: z.string().optional().describe("Free-text search across title, description, location, and amenities."),
    location: z.string().optional().describe("Filter by country/region (e.g. 'UK', 'United States')."),
    certification: z.enum(["all", "Certified", "Self-Reported", "Partner", "Pending"]).optional().describe("Certification filter."),
    minNeuroScore: z.number().min(0).max(100).optional().describe("Minimum neuro-inclusivity score (0-100)."),
    limit: z.number().min(1).max(50).default(20).describe("Maximum number of results to return (1-50)."),
    offset: z.number().min(0).default(0).describe("Pagination offset.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, location, certification, minNeuroScore, limit, offset }) => {
    const supabase = createPublicSupabase();
    let builder = supabase.from("listings").select("*", { count: "exact" });
    if (certification && certification !== "all") {
      builder = builder.eq("certification", certification);
    }
    if (typeof minNeuroScore === "number") {
      builder = builder.gte("neuro_score", minNeuroScore);
    }
    if (location?.trim()) {
      builder = builder.ilike("location", `%${location.trim()}%`);
    }
    if (query?.trim()) {
      const term = query.trim().toLowerCase();
      builder = builder.or(`title.ilike.%${term}%,description.ilike.%${term}%,location.ilike.%${term}%`);
    }
    const { data, error, count } = await builder.order("neuro_score", { ascending: false }).range(offset, offset + limit - 1);
    if (error) {
      return { content: [{ type: "text", text: `Database error: ${error.message}` }], isError: true };
    }
    const spaces = (data || []).map((item) => ({
      id: item.id,
      title: item.title,
      description: item.description,
      location: item.location,
      neuro_score: item.neuro_score,
      user_rating: item.user_rating,
      certification: item.certification,
      price: item.price,
      capacity: item.capacity,
      image_url: item.image_url,
      amenities: Array.isArray(item.amenities) ? item.amenities : []
    }));
    return {
      content: [
        {
          type: "text",
          text: `Found ${count ?? spaces.length} space(s). Showing ${spaces.length} result(s) starting at offset ${offset}.`
        },
        {
          type: "text",
          text: JSON.stringify({ total: count ?? spaces.length, offset, limit, spaces }, null, 2)
        }
      ]
    };
  }
});

// src/lib/mcp/tools/get-space-details.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.52.1";
import { z as z2 } from "npm:zod@^3.23.8";
function createPublicSupabase2() {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_space_details_default = defineTool2({
  name: "get_space_details",
  title: "Get workspace details",
  description: "Return the full neuro-accessibility profile for a single workspace by its ID, including amenities, sensory features, pricing, capacity, hours, certification, and community rating.",
  inputSchema: {
    id: z2.string().uuid().describe("The UUID of the workspace listing.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createPublicSupabase2();
    const { data, error } = await supabase.from("listings").select("*").eq("id", id).single();
    if (error) {
      return { content: [{ type: "text", text: `Database error: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `Workspace ${id} not found.` }], isError: true };
    }
    const space = {
      id: data.id,
      title: data.title,
      description: data.description,
      full_description: data.full_description,
      location: data.location,
      neuro_score: data.neuro_score,
      user_rating: data.user_rating,
      certification: data.certification,
      price: data.price,
      capacity: data.capacity,
      hours_of_operation: data.hours_of_operation,
      image_url: data.image_url,
      amenities: Array.isArray(data.amenities) ? data.amenities : []
    };
    return {
      content: [
        {
          type: "text",
          text: `${space.title} \u2014 ${space.location} (Neuro Score: ${space.neuro_score}/100, Rating: ${space.user_rating}/5)`
        },
        { type: "text", text: JSON.stringify(space, null, 2) }
      ]
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "neuroindex",
  title: "NeuroIndex Directory",
  version: "1.0.0",
  instructions: "Public read-only tools for the NeuroIndex directory of neuro-friendly workspaces, coworking spaces, and meeting rooms. Use `search_spaces` to discover spaces and `get_space_details` to retrieve the full profile for a specific listing.",
  tools: [search_spaces_default, get_space_details_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
