// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbylujrthjyryngdbiwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpieWx1anJ0aGp5cnluZ2RiaXd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Njg5NDYsImV4cCI6MjA2OTA0NDk0Nn0.FePp3ky2TL0jxk8WFdW1C-n71dpGYLHqjNTwoOWKvAk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});