name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build and generate static pages
        run: |
          echo "Building project and generating static pages..."
          node scripts/build-static.js
        env:
          NODE_ENV: production
        
      - name: Verify build output
        run: |
          echo "Verifying build completed successfully..."
          ls -la dist/
          echo "Checking for main files..."
          test -f dist/index.html && echo "✓ index.html found" || echo "✗ index.html missing"
          test -f dist/sitemap.xml && echo "✓ sitemap.xml found" || echo "✗ sitemap.xml missing"
          test -d dist/assets && echo "✓ assets directory found" || echo "✗ assets directory missing"
          
          echo "Checking static page generation..."
          test -f dist/about.html && echo "✓ about.html generated" || echo "✗ about.html missing"
          test -f dist/how-it-works.html && echo "✓ how-it-works.html generated" || echo "✗ how-it-works.html missing"
          test -f dist/spaces.html && echo "✓ spaces.html generated" || echo "✗ spaces.html missing"
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4