name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build and generate static pages
        run: |
          echo "Building project and generating static pages..."
          node scripts/build-static.js
        env:
          NODE_ENV: production
          CI: true
        
      - name: Verify build output
        run: |
          echo "Verifying build completed successfully..."
          ls -la dist/
          echo "Checking for main files..."
          test -f dist/index.html && echo "✓ index.html found" || echo "✗ index.html missing"
          test -f dist/sitemap.xml && echo "✓ sitemap.xml found" || echo "✗ sitemap.xml missing"
          test -d dist/assets && echo "✓ assets directory found" || echo "✗ assets directory missing"
          
          echo "Checking static page generation..."
          test -f dist/about/index.html && echo "✓ about/index.html generated" || echo "✗ about/index.html missing"
          test -f dist/how-it-works/index.html && echo "✓ how-it-works/index.html generated" || echo "✗ how-it-works/index.html missing"
          test -f dist/spaces/index.html && echo "✓ spaces/index.html generated" || echo "✗ spaces/index.html missing"
          test -f dist/contact/index.html && echo "✓ contact/index.html generated" || echo "✗ contact/index.html missing"
          test -f dist/resources/index.html && echo "✓ resources/index.html generated" || echo "✗ resources/index.html missing"
          test -f dist/workspace-providers/index.html && echo "✓ workspace-providers/index.html generated" || echo "✗ workspace-providers/index.html missing"
          test -f dist/404.html && echo "✓ 404.html generated" || echo "✗ 404.html missing"
          
          echo "Static pages successfully generated with proper SEO structure!"
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4